name: Update Catalogue

on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "data/**"
      - "scripts/**"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-:

      - name: Prepare runtime
        run: |
          cd ./scripts
          pip install -r requirements.txt

      - name: Generate output
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          cd ./scripts
          python gen.py

      - name: Deploy pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: page
          FOLDER: output/page
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SQUASH_HISTORY: false
          SKIP_EMPTY_COMMITS: true

      - name: Push diffs
        run: |
          cd ./output/diff
          for lang in en_us zh_cn
          do
            cd $lang
            git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git push origin master:diff/$lang --force
            cd ..
          done
